import React from "react";
import NotificationClient from "./components/NotificationClient";
import { Metadata } from "next";
import { fetchNotifications } from "@/actions/notification.actions";
import { getCurrentSession } from "@/actions/data.actions";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Nomeo 5.1 | Notifications",
  description: "Generated by create next app",
};

const NotificationsPage = async() => {
  const session = await getCurrentSession();
  
  if (!session?.user?.email) {
    redirect('/sign-in')
  }

  const notifications = await fetchNotifications();

  return <NotificationClient notifications={notifications} />;
};

export default NotificationsPage;
