import React from "react";
import FriendClient from "./components/FriendClient";
import { Metadata } from "next";
import { fetchSuggestedUsers, fetchUserFriends } from "@/actions/user.actions";
import { getCurrentSession, getCurrentUser } from "@/actions/data.actions";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Nomeo 5.1 | Friends",
  description: "Generated by create next app",
};

const FriendsPage = async () => {

  const session = await getCurrentSession();
  
  if (!session?.user?.email) {
    redirect('/sign-in')
  }

  const friends = await fetchUserFriends();
  const suggestedFriends = await fetchSuggestedUsers();
  const user = await getCurrentUser();
  const currentUser = JSON.parse(JSON.stringify(user));

  return <FriendClient friends={friends} suggestedFriends={suggestedFriends} currentUser={currentUser}/>;
};

export default FriendsPage;
