import React from "react";
import EditProfileClient from "./components/EditProfileClient";
import { getCurrentSession, getCurrentUser } from "@/actions/data.actions";
import { redirect } from "next/navigation";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Nomeo 5.1 | Edit Profile",
  description: "Generated by create next app",
};

type Props = {};

const EditProfilePage = async (props: Props) => {
  const user = await getCurrentUser();
  const currentUser = JSON.parse(JSON.stringify(user));

  const session = await getCurrentSession();
  
  if (!session?.user?.email) {
    redirect('/sign-in')
  }
  
  return <EditProfileClient currentUser={currentUser} />;
};

export default EditProfilePage;
