import React from "react";
import ProfileClient from "../components/ProfileClient";
import { fetchFriends, fetchUserById } from "@/actions/user.actions";
import { getCurrentSession, getCurrentUser } from "@/actions/data.actions";
import { redirect } from "next/navigation";
import { fetchUserAlbum, fetchUserPosts, fetchUserReposts } from "@/actions/post.action";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Nomeo 5.1 | Profile",
  description: "Generated by create next app",
};

type profilePageProps = {
  params: { id: string } 
};

const ProfilePage = async ({params}: profilePageProps) => {
  const { id } = params;

  const user = await fetchUserById(id);
  const currentuser = await getCurrentUser();
  const userPosts = await fetchUserPosts(id);
  const userReposts = await fetchUserReposts(id);
  const userAlbum = await fetchUserAlbum(id);
  const userFriends = await fetchFriends(id)

  const currentUser = JSON.parse(JSON.stringify(currentuser));

  const session = await getCurrentSession();
  
  if (!session?.user?.email) {
    redirect('/sign-in')
  }

  return <ProfileClient user={user} currentUser={currentUser} userPosts={userPosts} userReposts={userReposts} userAlbum={userAlbum} userFriends={userFriends}/>;
};

export default ProfilePage;
