import React from "react";
import PageContent from "./components/PageContent";
import { getCurrentSession } from "@/actions/data.actions";
import { redirect } from "next/navigation";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Nomeo 5.1 | Sign Up",
  description: "Generated by create next app",
};

const SignUpPage = async() => {
  const session = await getCurrentSession();

  if (session?.user?.email) {
    redirect('/');
  }

  return <PageContent />;
};

export default SignUpPage;
