import React from "react";
import SearchClient from "./components/SearchClient";
import { fetchAllUsers } from "@/actions/user.actions";
import { getCurrentSession, getCurrentUser } from "@/actions/data.actions";
import { redirect } from "next/navigation";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Nomeo 5.1 | Search",
  description: "Generated by create next app",
};


const SearchPage = async({searchParams}: {searchParams: { [key: string]: string | undefined }}) => {
  const session = await getCurrentSession();
  
  if (!session?.user?.email) {
    redirect('/sign-in')
  }

  const { query } = searchParams;

  const results = await fetchAllUsers({query : query as string});

  const users = await getCurrentUser();

  const currentUser = JSON.parse(JSON.stringify(users))

  return <SearchClient searchResults={results} currentUser={currentUser}/>;
};

export default SearchPage;
