import React from "react";
import PostClient from "../components/PostClient";
import { fetchSinglePost } from "@/actions/post.action";
import { getCurrentSession, getCurrentUser } from "@/actions/data.actions";
import { rawUserData } from "@/types";
import { fetchComments } from "@/actions/comment.actions";
import { redirect } from "next/navigation";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Nomeo 5.1 | Comments",
  description: "Generated by create next app",
};

type commentPageProps = {
  params: { id: string } 
};

const CommentPage = async ({params}: commentPageProps) => {

  const post = await fetchSinglePost(params.id)
  const user = await getCurrentUser();
  const comments = await fetchComments(params.id);
  
  const currentUser = JSON.parse(JSON.stringify(user));

  const session = await getCurrentSession();
  
  if (!session?.user?.email) {
    redirect('/sign-in')
  }

  return <PostClient post={post} currentUser={currentUser as rawUserData} comments={comments}/>;
};

export default CommentPage;
