import type { Metadata } from "next";
import localFont from 'next/font/local'
import "../globals.css";
import ToastProvider from "@/providers/ToastProvider";

const customFont = localFont({src: '../../public/fonts/Barlow-Regular.ttf'});

export const metadata: Metadata = {
  title: "Nomeo 5.1",
  description: "Generated by create next app",
};

export default function MainAuthLayout({children}:{children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={customFont.className}>
        <div className="absolute">
          <ToastProvider />
        </div>
        {children}
      </body>
    </html>
  );
}
