import React from 'react'
import { Metadata } from 'next';
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Nomeo 5.1 | Not Found",
  description: "Generated by create next app",
};

const customFont = localFont({ src: "../../../public/fonts/Barlow-Regular.ttf" });

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={customFont.className}>
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}