import React from "react";
import SavedPostClient from "./components/SavedPostClient";
import { Metadata } from "next";
import { getCurrentSession, getCurrentUser } from "@/actions/data.actions";
import { redirect } from "next/navigation";
import { fetchSavedPosts } from "@/actions/post.action";

export const metadata: Metadata = {
  title: "Nomeo 5.1 | Saved Posts",
  description: "Generated by create next app",
};


const SavedPostsPage = async () => {
  const savedPosts = await fetchSavedPosts();
  const user = await getCurrentUser();
  const currentUser = JSON.parse(JSON.stringify(user))

  const session = await getCurrentSession();
  
  if (!session?.user?.email) {
    redirect('/sign-in')
  }

  return <SavedPostClient savedPost={savedPosts} currentUser={currentUser}/>;
};

export default SavedPostsPage;
